### ISSUE TITLE
Update step with a single radar observation

### ISSUE THREAD

**Issue by Amith4504** [TomLKoller/Boxplus-IMM#2]
As I went through your code and did some runs, I observed that the the estimation RMSE depends on the number of radar landmarks that I give. Default is 4 , but when i reduce to 2 landmarks the accuracy decreases. Are there radars mimicing muliple radar units at different positions ? . Also , in the update step , is it updating 4 times corresponding to 4 radar sensors ? Why is accuracy so bad for single radar sensor?

**Comment by TomLKoller** [comment]
> Are there radars mimicing muliple radar units at different positions ? 

I am not sure what you mean exactly. Each of the 4 radars has a unique position.

> Also , in the update step , is it updating 4 times corresponding to 4 radar sensors ?

  The update step is performed on the combination of  all 4 radar measurements. So it is updates once per cycle. 

> Why is accuracy so bad for single radar sensor?

In general, more radars improve accuracy, since random errors are averaged. The issue with one radar sensor is that the systems state is unobservable, i.e. ambigious  (at least in the immBodyDistance example).

**Comment by Amith4504** [comment]
Thanks for the reply.  It cleared the confusion regarding mutiple radars. 
Also I had a question which is unrelated to the issue. I tried using the  "predictwithoutAdditiveNoise( )" step mutiple times without  a measurement update. By definition the mean of the states should change with mutiple consecutive predict steps without a observation update , since the states go through the transition matrix or motion models. But the mean of states do not seem to change . Am i missing something ?

**Comment by TomLKoller** [comment]
The output of the  imm is only updated when calling combination. You can call combination without update().
Predict and update only change the inner filter estimates and the model probabilities. You can access the inner filter estimates by:
imm.getFilter(index).mu or .sigma


This is the desired behavior of the IMM as in https://ieeexplore.ieee.org/document/251886

( or in Table I of our OA paper https://www.mdpi.com/1424-8220/21/12/4164 if you dont have access to the paywall).

**Comment by Amith4504** [comment]
Yes , Thank you so much for the help .
